name: release-docker
on:
  release:
    types: published

jobs:
  docker-image:
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'v2')
    strategy:
      matrix:
        build:
          - scratch
          - alpine
        include:
          - build: scratch
            os: ubuntu-20.04
          - build: alpine
            os: ubuntu-20.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Docker meta scratch
        id: meta_scratch
        if: matrix.build == 'scratch'
        uses: docker/metadata-action@v3
        with:
          images: joseluisq/static-web-server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Docker meta alpine
        id: meta_alpine
        uses: docker/metadata-action@v3
        if: matrix.build == 'alpine'
        with:
          images: joseluisq/static-web-server
          flavor: |
            latest=false
            suffix=alpine
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Prepare Docker envs
        shell: bash
        run: |
          echo "SERVER_VERSION=${GITHUB_REF##v}" >> $GITHUB_ENV
          echo "SERVER_DOCKERFILE=./docker/${{ matrix.build }}/Dockerfile" >> $GITHUB_ENV
      -
        name: Build and push (scratch)
        uses: docker/build-push-action@v2
        if: matrix.build == 'scratch'
        with:
          push: true
          context: .
          file: ${{ env.SERVER_DOCKERFILE }}
          tags: ${{ steps.meta_scratch.outputs.tags }}
          build-args: |
            SERVER_VERSION=${{ env.SERVER_VERSION }}
      -
        name: Build and push (alpine)
        uses: docker/build-push-action@v2
        if: matrix.build == 'alpine'
        with:
          push: true
          context: .
          file: ${{ env.SERVER_DOCKERFILE }}
          tags: ${{ steps.meta_alpine.outputs.tags }}
          build-args: |
            SERVER_VERSION=${{ env.SERVER_VERSION }}
